apiVersion: apps/v1
kind: Deployment
metadata:
  name: achat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: achat-app
  template:
    metadata:
      labels:
        app: achat-app
    spec:
      containers:
        - name: achat-app
          image: 23153122e351/test
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysqldb
            - name: DB_NAME
              value: crud-db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: Password123
