apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-builds
spec:
  workspaces:
  - name: k8s
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
  params:
  - name: image
    description: Reference of the image docker will produce.
  - name: context
    description: Path to the directory to use as context.
    default: .
  steps:
  - name: docker-builds
    image: docker.io/library/docker:stable@sha256:18ff92d3d31725b53fa6633d60bed323effb6d5d4588be7b547078d384e0d4bf
    env:
    - name: DOCKER_HOST
      value: unix:///var/run/docker.sock
    workingDir: /workspace/shared-data
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
    script: |
      docker build --no-cache -t $(params.image) $(params.context)

